### PR TITLE
Add "Now" page

### PR DESCRIPTION
**Pull request by jchristgit**

### CODE REVIEW

**Comment by jb3** [comment]
Can you update your branch to include the latest changes from main, notably the staging CI flow?

**Comment by jchristgit** [comment]
Done, please approve workflow.

**Comment by jb3** [comment]
I have identified a problem.

**Comment by jchristgit** [comment]
I pushed another commit with information about the recent deployment of love letters directed towards Jeremiah.

If you want something else changed here, please let me know.

**Comment by jchristgit** [comment]
Updated with information about the PyDis postfix forwarding setup.

**Comment by jchristgit** [comment]
Updated with information about the PyDis documentation and our e-mail services.

**Review by jb3 — APPROVED** [review]

**Pull request merged**
